Velodyne tf and tf_static should be remapped to the robot namespace
clearpathrobotics/clearpath_robot pull request #102
Opened 2024-11-19 10:41 UTC by marco-ambrosio

I think that, as it happens for all the other sensors, the topics /tf and /tf_static should be remapped to the namespace of the robot.

2024-11-21 20:12 UTC, hilary-luo requested changes
Thank you very much for contributing! I have a couple of quick requests and then we can get this fix merged in.

2024-11-21 20:12 UTC, hilary-luo commented on clearpath_sensors/launch/velodyne_lidar.launch.py
> +          ('/diagnostics', 'diagnostics'), ('/tf', 'tf'), ('/tf_static', 'tf_static')
The new remaps should not be here as the velodyne driver node does not use those topics

2024-11-21 20:12 UTC, hilary-luo commented on clearpath_sensors/launch/velodyne_lidar.launch.py
> +          ('/diagnostics', 'diagnostics'), ('/tf', 'tf'), ('/tf_static', 'tf_static')
Can you please put each remap on a new line to be consistent with our other launch files

2024-11-25 21:21 UTC, civerachb-cpr approved these changes
Looks OK to me. The CI failures look to be an unrelated issue we can tackle separately.

2024-11-25 21:22 UTC, merged