VCan Service
clearpathrobotics/clearpath_robot pull request #70
Opened 2024-07-29 14:27 UTC by luis-camero

2024-07-29 18:26 UTC, tonybaltovski requested changes

2024-07-29 18:26 UTC, tonybaltovski commented on clearpath_robot/scripts/vcan
> +#!/bin/bash
Add a license here.

2024-07-31 13:46 UTC, roni-kreinin commented on clearpath_robot/scripts/install
> +PUMA_ENABLED = [
Can we rename puma enabled to just can enabled? Its not specific to pumas

2024-08-09 15:05 UTC, tonybaltovski approved these changes

2024-08-09 15:06 UTC, merged